import { StyleSheet } from 'react-native';

export default styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF', // Fundo branco para um visual mais clean e moderno
        padding: 20,
    },
    logoText: {
        fontSize: 38,
        fontWeight: 'bold',
        color: '#222',
        textTransform: 'uppercase',
        marginBottom: 40,
        letterSpacing: 3,
    },
    gridContainer: {
        width: '100%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        paddingHorizontal: 10,
    },
    square: {
        width: 160,
        height: 160,
        backgroundColor: '#F8F9FA',
        borderRadius: 15,
        justifyContent: 'center',
        alignItems: 'center',
        margin: 12,
        shadowColor: '#000',
        shadowOpacity: 0.15,
        shadowOffset: { width: 0, height: 5 },
        elevation: 5,
        borderWidth: 2,
        borderColor: '#DDD',
    },
    squareText: {
        color: '#222',
        fontSize: 20,
        fontWeight: '600',
        textAlign: 'center',
    },
    input: {
        width: '90%',
        height: 50,
        backgroundColor: '#FFF',
        borderRadius: 12,
        paddingHorizontal: 20,
        fontSize: 18,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 3 },
        elevation: 3,
        borderWidth: 1,
        borderColor: '#CCC',
    },
    addButton: {
        position: 'absolute',
        bottom: 30,
        backgroundColor: '#007BFF',
        paddingVertical: 16,
        paddingHorizontal: 40,
        borderRadius: 30,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.25,
        shadowOffset: { width: 0, height: 5 },
        elevation: 8,
        transition: '0.3s',
    },
    addButtonText: {
        color: '#FFF',
        fontSize: 20,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    cardContainer: {
        width: '90%',
        backgroundColor: '#FFF',
        borderRadius: 12,
        padding: 15,
        marginBottom: 15,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 3 },
        elevation: 4,
        borderWidth: 1,
        borderColor: '#DDD',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    iconContainer: {
        flexDirection: 'row',
        gap: 10,
    },
    groupBtn: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 5,
    },
});
